language: android
jdk: oraclejdk8
sudo: false

notifications:  #Optional
    email:
        - whitmadm@gmail.com #Add your email address

env:
  - ANDROID_TARGET=android-25
  - BUILD_TOOLS=25.0.0

android:
    components:
        - platform-tools
        - tools
        - build-tools-$BUILD_TOOLS    #Build tool version
        - android-$ANDROID_TARGET            #target api version

        # Additional components
        # - extra-google-google_play_services
        # - extra-google-m2repository
        # - extra-android-m2repository
        
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - ./gradlew testDebugUnitTest
  - ./gradlew assembleDebug